// ==============================================================================
// Yoga24X AI Engineering OS — Auth Constants & Security Configs
// ==============================================================================

export const AUTH_CONSTANTS = {
  // Token Lifetimes
  ACCESS_TOKEN_TTL_SECONDS: 900, // 15 minutes (RS256 short-lived)
  REFRESH_TOKEN_TTL_SECONDS: 604800, // 7 days (Family rotation)
  OTP_TTL_SECONDS: 300, // 5 minutes
  OTP_LENGTH: 6,
  OTP_MAX_ATTEMPTS: 5,
  ACCOUNT_LOCK_DURATION_SECONDS: 1800, // 30 minutes after max failed attempts
  MAX_FAILED_LOGIN_ATTEMPTS: 5,

  // Redis Key Prefixes
  REDIS_KEY_SESSION_PREFIX: 'yoga24x:session:',
  REDIS_KEY_REFRESH_FAMILY_PREFIX: 'yoga24x:refresh_family:',
  REDIS_KEY_JTI_BLACKLIST_PREFIX: 'yoga24x:blacklist:jti:',
  REDIS_KEY_OTP_PREFIX: 'yoga24x:otp:',
  REDIS_KEY_OTP_ATTEMPTS_PREFIX: 'yoga24x:otp_attempts:',
  REDIS_KEY_RATE_LIMIT_PREFIX: 'yoga24x:rate_limit:',
  REDIS_KEY_ACCOUNT_LOCK_PREFIX: 'yoga24x:lock:user:',
  REDIS_KEY_FAILED_LOGINS_PREFIX: 'yoga24x:failed_logins:',
  REDIS_KEY_RISK_SCORE_PREFIX: 'yoga24x:risk_score:',
  REDIS_KEY_DISTRIBUTED_LOCK_PREFIX: 'yoga24x:dlock:',

  // Cookie Names
  COOKIE_ACCESS_TOKEN: 'y24x_access_token',
  COOKIE_REFRESH_TOKEN: 'y24x_refresh_token',
  COOKIE_DEVICE_FINGERPRINT: 'y24x_device_fp',

  // Headers
  HEADER_DEVICE_ID: 'x-device-id',
  HEADER_DEVICE_TYPE: 'x-device-type',
  HEADER_DEVICE_NAME: 'x-device-name',
  HEADER_DEVICE_FINGERPRINT: 'x-device-fingerprint',
  HEADER_APP_VERSION: 'x-app-version',
  HEADER_OS_VERSION: 'x-os-version',
  HEADER_IDEMPOTENCY_KEY: 'x-idempotency-key',
  HEADER_REAL_IP: 'x-real-ip',
  HEADER_FORWARDED_FOR: 'x-forwarded-for',

  // Security & Audit Actions
  AUDIT_ACTION_LOGIN_SUCCESS: 'AUTH_LOGIN_SUCCESS',
  AUDIT_ACTION_LOGIN_FAILED: 'AUTH_LOGIN_FAILED',
  AUDIT_ACTION_LOGOUT: 'AUTH_LOGOUT',
  AUDIT_ACTION_LOGOUT_ALL: 'AUTH_LOGOUT_ALL_DEVICES',
  AUDIT_ACTION_TOKEN_REFRESH: 'AUTH_TOKEN_REFRESH',
  AUDIT_ACTION_TOKEN_REUSE_DETECTED: 'AUTH_TOKEN_REUSE_THEFT_DETECTED',
  AUDIT_ACTION_OTP_REQUESTED: 'AUTH_OTP_REQUESTED',
  AUDIT_ACTION_OTP_VERIFIED: 'AUTH_OTP_VERIFIED',
  AUDIT_ACTION_OTP_FAILED: 'AUTH_OTP_FAILED',
  AUDIT_ACTION_ACCOUNT_LOCKED: 'AUTH_ACCOUNT_LOCKED',
  AUDIT_ACTION_ACCOUNT_UNLOCKED: 'AUTH_ACCOUNT_UNLOCKED',
  AUDIT_ACTION_PASSWORD_CHANGED: 'AUTH_PASSWORD_CHANGED',
  AUDIT_ACTION_PASSWORD_RESET_REQUESTED: 'AUTH_PASSWORD_RESET_REQUESTED',
  AUDIT_ACTION_BIOMETRIC_REGISTERED: 'AUTH_BIOMETRIC_REGISTERED',
  AUDIT_ACTION_BIOMETRIC_LOGIN: 'AUTH_BIOMETRIC_LOGIN',
  AUDIT_ACTION_DEVICE_TRUSTED: 'AUTH_DEVICE_TRUSTED',
  AUDIT_ACTION_DEVICE_REVOKED: 'AUTH_DEVICE_REVOKED',
  AUDIT_ACTION_SUSPICIOUS_LOGIN_DETECTED: 'AUTH_SUSPICIOUS_LOGIN_DETECTED',

  // Risk Scoring Thresholds
  RISK_SCORE_LOW_THRESHOLD: 25,
  RISK_SCORE_MEDIUM_THRESHOLD: 50,
  RISK_SCORE_HIGH_THRESHOLD: 75,
  RISK_SCORE_BLOCK_THRESHOLD: 90,
} as const;

export type AuthAuditAction = (typeof AUTH_CONSTANTS)[keyof typeof AUTH_CONSTANTS];
