// ==============================================================================
// Yoga24X AI Engineering OS — IAM & User Management Constants
// ==============================================================================

export const IAM_CONSTANTS = {
  PROFILE_COMPLETION_WEIGHTS: {
    BASIC_INFO: 30,
    CONTACT_VERIFIED: 20,
    ROLE_SPECIFIC_PROFILE: 30,
    AVATAR_UPLOADED: 10,
    PRIVACY_CONSENT: 10,
  },
  MAX_AVATAR_SIZE_BYTES: 5 * 1024 * 1024, // 5MB
  MAX_COVER_SIZE_BYTES: 10 * 1024 * 1024, // 10MB
  ALLOWED_IMAGE_MIMES: ['image/jpeg', 'image/png', 'image/webp'],
  VERIFICATION_TYPES: [
    'EMAIL',
    'PHONE',
    'GOVERNMENT_ID',
    'TEACHER_CERT',
    'DOCTOR_REG',
    'STUDIO_REG',
    'CORPORATE_REG',
  ] as const,
  VERIFICATION_STATUSES: [
    'PENDING',
    'IN_REVIEW',
    'APPROVED',
    'REJECTED',
    'RESUBMISSION_REQUIRED',
  ] as const,
  ORGANIZATION_ROLES: ['OWNER', 'ADMIN', 'MEMBER'] as const,
  ORGANIZATION_TYPES: ['STUDIO', 'CORPORATE'] as const,
  CONSENT_TYPES: [
    'TERMS_OF_SERVICE',
    'PRIVACY_POLICY',
    'COOKIE_PREFERENCES',
    'MARKETING_COMMUNICATIONS',
    'AI_COACHING',
    'HEALTH_DATA_PROCESSING',
  ] as const,
  ACCOUNT_STATUSES: ['ACTIVE', 'SUSPENDED', 'PENDING_VERIFICATION', 'DELETED'] as const,
  ERROR_CODES: {
    USER_NOT_FOUND: 'IAM_404_USER_NOT_FOUND',
    PROFILE_NOT_FOUND: 'IAM_404_PROFILE_NOT_FOUND',
    ORG_NOT_FOUND: 'IAM_404_ORG_NOT_FOUND',
    UNAUTHORIZED_ORG_ACCESS: 'IAM_403_UNAUTHORIZED_ORG_ACCESS',
    VERIFICATION_ALREADY_APPROVED: 'IAM_409_VERIFICATION_ALREADY_APPROVED',
    INVALID_IMAGE_FORMAT: 'IAM_400_INVALID_IMAGE_FORMAT',
    CANNOT_DELETE_ONLY_OWNER: 'IAM_400_CANNOT_DELETE_ONLY_OWNER',
  },
} as const;
